<project>
  <modelVersion>4.0.0</modelVersion>
  <parent>
    <groupId>example.overview</groupId>
    <artifactId>overview-parent</artifactId>
    <version>1.0.0</version>
    <relativePath>../parent/pom.xml</relativePath>
  </parent>
  <artifactId>overview-starter</artifactId>
  <dependencies>
    <dependency>
      <groupId>example.overview</groupId>
      <artifactId>overview-core</artifactId>
      <version>1.0.0</version>
    </dependency>
  </dependencies>
</project>
